### PR TITLE
fix(deps): Allow protobuf 5

### PR DESCRIPTION
**Pull request by mtnpke**

### CODE REVIEW

**Comment by BaxHugh** [comment]
Thanks for the PR @mtnpke.
I'd love it if this could be merged and release please @cpcloud ! (assuming no tests show there are problems)

I'll add that I haven't had any problems using protol with python protobuf 5.

**Comment by rtzoeller** [comment]
@cpcloud is this something you'll have time to look at in the near future? Thanks!

**Comment by Jazzinghen** [comment]
If possible I would remove the upper bounds altogether so that we don't have to wait for an update until there is an actual bug.

**Comment by pdonorio** [comment]
This is really much needed. Any reason the checks are all pending?

**Comment by BaxHugh** [comment]
Friendly ping on this PR @cpcloud

**Comment by cpcloud** [comment]
Addressing this in #1035.

**Pull request closed without merging**
